# Generated by Django 4.2 on 2023-04-08 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_involved', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timeline.event')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_involved', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timeline.event')),
                ('organization_involved', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timeline.organization')),
            ],
        ),
    ]
