# Generated by Django 4.2 on 2023-05-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_remove_organization_event_involved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='event_involved',
            field=models.ManyToManyField(to='timeline.event'),
        ),
        migrations.AlterField(
            model_name='person',
            name='event_involved',
            field=models.ManyToManyField(to='timeline.event'),
        ),
        migrations.AlterField(
            model_name='person',
            name='organization_involved',
            field=models.ManyToManyField(to='timeline.organization'),
        ),
    ]
