# Generated by Django 4.2 on 2023-05-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_alter_organization_event_involved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='organization_involved',
            new_name='organizations_involved',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='event_involved',
        ),
        migrations.RemoveField(
            model_name='person',
            name='event_involved',
        ),
        migrations.AddField(
            model_name='event',
            name='organizations_involved',
            field=models.ManyToManyField(to='timeline.organization'),
        ),
        migrations.AddField(
            model_name='event',
            name='persons_involved',
            field=models.ManyToManyField(to='timeline.person'),
        ),
    ]
