# Generated by Django 4.2 on 2023-07-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizations_involved',
            field=models.ManyToManyField(null=True, to='timeline.organization'),
        ),
        migrations.AlterField(
            model_name='event',
            name='persons_involved',
            field=models.ManyToManyField(null=True, to='timeline.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='organizations_involved',
            field=models.ManyToManyField(null=True, to='timeline.organization'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='events',
            field=models.ManyToManyField(null=True, to='timeline.event'),
        ),
    ]
